---
title: "Aristatoma_trees"
output: html_document
date: "2025-06-26"
---

```{r}

### Multispecies coalescent tree for selected set of 34 taxa (Pleosporaceae, Coniothyriaceae, related spp.). Fig. 1

library(phytools)
library(ggtree)
library(glue)

#############################
#SET WD!!!!
#############################

#e.g.....
setwd('/90daydata/fdwsru_fungal/Nick/dothideos/BUSCO_tree/03_tree')

tree <- read.tree('FIG1_tree.nwk')
#tree <- midpoint.root(tmp)

df <-read.table("FIG1_datatable.tsv", header = TRUE)
df$Type[df$Type == TRUE] <- "T"
df <- dplyr::mutate(df, lab = glue("~italic({Genus})~~italic({Species})~~{nonitalic1}~{nonitalic2}~italic({subsp})~{Assembly}~{Type}"))

fontsize=3
textsize=3

p<- ggtree(tree)  %<+% df +
  geom_tiplab(
    aes(label = lab, color = Family), 
    linesize = .15,
    geom = "label",
    label.size = 0,
    label.padding = unit(0, "lines"),
    parse = TRUE,
    size = fontsize,
    show.legend = TRUE,
    align = TRUE
  ) +
  ggplot2::xlim(0, 1) + 
  geom_treescale()

# view plot in RStudio and adjust dimensions of export setting as needed.
```

``` {r}

## Script to generate ITS tree from maximum likelihood analysis (Fig. 2)

#############################
#SET WD!!!!
#############################

#e.g.....
setwd('/90daydata/fdwsru_fungal/Nick/dothideos/BUSCO_tree/03_tree')


library(phytools)
library(ggtree)
library(glue)

tree <- read.tree('ITS28Stree_ML.nwk')
tree <- root(tree, "Paraleptosphaeria_praetermissa_CBS114591", resolve.root = TRUE)

df <- read.csv('ITS28S_data.csv')
df$Type[df$Type == TRUE] <- "T"
df <- dplyr::mutate(df, lab = glue("~{nonitalic1}~italic({Genus})~italic({Species})~{nonitalic2}~{Type}"))


q <- ggtree(tree)
d <- q$data
d <- d[!d$isTip,]
d$label2 <- as.numeric(d$label)
d2 <- d[d$label2>70,]


p <- ggtree(tree)  %<+% df +
  geom_tiplab(
    aes(label = lab), 
    linesize = .15,
    geom = "label",
    label.size = 0,
    label.padding = unit(0, "lines"),
    parse = TRUE,
    size = 2.5,
    show.legend = FALSE,
    align = TRUE
  ) + 
  ggplot2::xlim(0,.25) 

p2 <- p %<+%d2 +geom_text2(aes(label = label2), size = 1.5, hjust = 1.5, vjust = -.5)

#add branch labels > 70 % support in powerpoint. Easier to add manually with few labels to keep tree visually appealing. See p2 to view branch labels on formatted tree.

# view plot in RStudio and adjust dimensions of export setting as needed.

```


```{r}

#script to generate tree for all Pleosporales spp. with selected other Dothideomycetes (Fig. S1)

#############################
#SET WD!!!!
#############################

#e.g.....
setwd('/90daydata/fdwsru_fungal/Nick/dothideos/BUSCO_tree/03_tree')


library(phytools)
library(ggtree)
library(glue)

tree <- read.tree('FIGS1_tree.nwk')
#tree <- midpoint.root(tmp)

df <- read.table("FIGS1_datatable.tsv", header = TRUE)
df <- dplyr::mutate(df, lab = glue("~italic({Genus})~~italic({Species})~~{nonitalic1}~{nonitalic2}~italic({subsp})~{Assembly}~{Family}"))

fontsize=2

p<- ggtree(tree)  %<+% df +
  geom_tiplab(
    aes(label = lab), 
    linesize = .15,
    geom = "label",
    label.size = 0,
    label.padding = unit(0, "lines"),
    parse = TRUE,
    size = fontsize,
    show.legend = FALSE,
    align = TRUE
  ) + xlim(0, 3)
  
# view plot in RStudio and adjust dimensions of export setting as needed.

```


```{r}

### Maximum likelihood tree for selected set of 34 taxa (Pleosporaceae, Coniothyriaceae, related spp.). Fig. S2

#############################
#SET WD!!!!
#############################

#e.g.....
setwd('/90daydata/fdwsru_fungal/Nick/dothideos/BUSCO_tree/03_tree')


library(phytools)
library(ggtree)
library(glue)

tree <- read.tree('FIGS2_tree.nwk')
tree <- root(tree, "Parastagonospora_nodorum_SN15", resolve.root = TRUE)

df <-read.table("FIG1_datatable.tsv", header = TRUE)
df$Type[df$Type == TRUE] <- "T"
df <- dplyr::mutate(df, lab = glue("~italic({Genus})~~italic({Species})~~{nonitalic1}~{nonitalic2}~italic({subsp})~{Assembly}~{Type}"))

q <- ggtree(tree)
d <- q$data
d <- d[!d$isTip,]
d$label2 <- as.numeric(d$label)

#adjust line below to filter for bootstrap values above or below a threshold
d2 <- d[d$label2<100,]

p <- ggtree(tree)  %<+% df +
  geom_tiplab(
    aes(label = lab, color = Family), 
    linesize = .15,
    geom = "label",
    label.size = 0,
    label.padding = unit(0, "lines"),
    parse = TRUE,
    size = fontsize,
    show.legend = TRUE,
    align = TRUE
  ) +
  ggplot2::xlim(0, .5) 
  
p2 <- p %<+%d2 +geom_text2(aes(label = label2), size = 1.5, hjust = 1.5, vjust = -.5)

# view p2 plot in RStudio and adjust dimensions of export setting as needed.
```
``` {r}

## Script to generate ITS/28 cladogram from maximum parsimony analysis (Fig. S3)

#############################
#SET WD!!!!
#############################

#e.g.....
setwd('/90daydata/fdwsru_fungal/Nick/dothideos/BUSCO_tree/03_tree')


library(phytools)
library(ggtree)
library(glue)

tree <- read.tree('ITS28Stree_MP.nwk')
df <- read.csv('ITS28S_data.csv')
df$Type[df$Type == TRUE] <- "T"
df <- dplyr::mutate(df, lab = glue("~{nonitalic1}~italic({Genus})~italic({Species})~{nonitalic2}~{Type}"))


q <- ggtree(tree)
d <- q$data
d <- d[!d$isTip,]
d$label2 <- round(as.numeric(d$label)*100)
d2 <- d[d$label2>70,]


p <- ggtree(tree)  %<+% df +
  geom_tiplab(
    aes(label = lab), 
    linesize = .15,
    geom = "label",
    label.size = 0,
    label.padding = unit(0, "lines"),
    parse = TRUE,
    size = 2.5,
    show.legend = FALSE,
    align = TRUE
  ) +xlim(0,15)

p2 <- p %<+% d2 + geom_text2(aes(label = label2), size = 2.5, hjust = 1.5, vjust = -.5)

# view p2 plot in RStudio and adjust dimensions of export setting as needed.

```